### ISSUE TITLE
Your software is excellent, but has some issue

### ISSUE THREAD

**Issue by newch0** [Tortar/PowerPointAudio-Extractor#1] opened 2020-11-03 22:28 UTC
Hi, I am the one of student who use your software very thankfully because of the COVID19.
First, I'm sorry to you because of my lack of English skill and knowledge about programming, but I will try my best to deliver my opinion logically.
I used your program properly, and I think your program is really helpful to student like me.
But I found that some(actually most of my lecture ppt)of ppt doesn't working on your program.
Of course I checked every mention of your manual(README).
Hence I tested a lot of situation of ppt.
I think(My hypothesis is) there are some compatibility issue, it doesn't seem working on pptx that made from office 365.
More specifically, your program was working when name of audio files(in "media folder in ppt.zip") is "audio1, audio2....and so on".(sorry for bad explanation, you better check the 2nd image below)
Most of lecture note edited from office 365 has a different audio files' name, such as "media1, media2.....and so on".(check 1st image below) and this case doesn't working on your program. It makes a empty "wav_files" folder and ppt file is converted to zip file.

It seems there are many students who have same issue, and this issue does not caused by difference of language in filename.(I tested and checked.). Although I am not profession in programming, but I strongly suggest this would have a some kind of compatibility issue, or a minor mistake in script.

I am one of lover of your software, hope this issue can be solved.
Thank you for read.
![figure a](https://user-images.githubusercontent.com/41482066/98047097-b19ca100-1e6e-11eb-9c73-7d89ff6a5006.jpg)
![figure b](https://user-images.githubusercontent.com/41482066/98047100-b2cdce00-1e6e-11eb-9137-1e91186b2d89.jpg)

**Comment by ameligrana** [comment] 2020-11-21 23:27
Hi! Sorry for the late reply but I'm not visiting github much. Thanks to your detailed issue, now I will examine the problem and see if I can come up with something to fix it!

by now i tried with something very similar to what you have posted, namely : 

![secodnv](https://user-images.githubusercontent.com/68152031/99890191-fe4cee00-2c5c-11eb-914f-bbd755ffa67b.PNG)

but it works :P

**Comment by Tortar** [comment] 2020-11-21 23:30
Ah it seems like the problem is really simple it's just that your extension is not considered to be a good one (.m4a) !

**Comment by ameligrana** [comment] 2020-11-22 00:18
I have invited you to become a collaborator, this can be really helpful because you can upload a file now , my idea is that you could put one of the powerpoint you mentioned inside this repository so that I have more chance to fix the issue, can you do it?

**Comment by newch0** [comment] 2020-12-05 14:34
Sure! Sorry for I applied late either.. 
This is one of the example that had not work.
[test.pptx](https://github.com/Tortar/PowerPointAudio-Extractor/files/5647212/test.pptx)

**Comment by newch0** [comment] 2020-12-05 14:51
Oh I found message in cmd too, it says:
"RuntimeWarning: Couldn't find ffmpeg or avconc - default
ting to ffmpeg. but may not work
Extracting...."

hope this could be help.

Also I realized that github's server down/uploading speed is not good while I upload file above.
Here is lighter version of issued file that has only two pages and minimized texts.
[test light.pptx](https://github.com/Tortar/PowerPointAudio-Extractor/files/5647242/test.light.pptx)

**Comment by ameligrana** [comment] 2020-12-05 17:06
So strange man, I ran the script...and it worked ! (I used the first)
Download the audio here: https://we.tl/t-cvviMtqbw2
Are you using the .exe script right? Do you have the latest version of the script? I would try to re-download it!

**Comment by newch0** [comment] 2020-12-06 03:19
I tried in another PC but it also failed..
For the record, I Ctrl V the ppt into "exe_extractor", and double clicked a"extractor.exe".
For me, this procedure makes:
1. zipped file of original ppt file.
2. empty "wav_files" folder.
3. "media" folder that filled with every audio files of ppt(but not merged).

It says  same message: "RuntimeWarning: Couldn't find ffmpeg or avconc - defaulting to ffmpeg. but may not work".

I am not developer, but I assume your script is working of this algorithm:
A. makes zip file of original ppt file.
B. extract audio files from zip file.
C. merge audio files.

Hence I strongly suggest your script(at least my environment) does the job of A and B, but failed to step forward to C.

I understand it is to hard to find difference of environment with you and me.

Here is my (bad) hypothesis.... I'm really sorry to you because I know nothing about coding. If I did, my hypothesis would be better.
Are there any software or options that developers would have and others doesn't? (Maybe ffmpeg stuff?)
Or it just occurs because of language difference of Windows?

**Comment by ameligrana** [comment] 2020-12-06 11:13
Mmmh strange because it's a .exe so it should work the same on every windows . I will try with another random computer without ffmpeg or avconc installed on your ppt and see

**Comment by newch0** [comment] 2020-12-06 14:41
Thanks! I'll wait for the result:)

**Comment by ameligrana** [comment] 2021-02-07 18:31
Sorry man unfortunately I forgot about this for a few months :PP but now I've tried and it worked so I close the issue anyway, hope it worked at the end on your computer :)

**Closed as completed by ameligrana** 2021-02-07 18:31 UTC

**Comment by ameligrana** [comment] 2021-03-08 23:17
Hi , I finally observed that the exe_extractor had some major issues so I left only the python script, it should work fine but you need to follow the setup to make it work

**Comment by newch0** [comment] 2021-03-09 04:04
Sure! Im so glad you fixed the error. Just tell me how, Im ready to follow
your guide.

2021년 3월 9일 (화) 오전 8:17, Tortar <notifications@github.com>님이 작성:

**Comment by ameligrana** [comment] 2021-03-09 18:01
the information are written on the main page of the script, if you find something not so clear tell me ( I didn't write it but you need to first install python)

**Comment by newch0** [comment] 2021-03-10 03:43
Thanks, I'll check it out.

2021년 3월 10일 (수) 오전 3:01, Tortar <notifications@github.com>님이 작성:
